version: "2"
services: 
  node:
    image: node
    container_name: node
    ports: 
      - 0.0.0.0:3132:3000
    working_dir: /www/src
    command: node index.js
  nginx: 
    image: nginx
    container_name: nginx
    ports: 
      - 0.0.0.0:80:80
      - 0.0.0.0:81:81
    networks: 
      - app
    volumes: 
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    ports:
      - 0.0.0.0:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    volumes:
      - ./data/mysql:/var/lib/mysql:ro
      - ./config/mysql/master_my.conf:/etc/mysql/my.cnf:ro
    networks:
      - app
networks:
  app:
    external: true