version: "2"
services: 
  node:
    image: node
    container_name: node
    ports: 
      - 0.0.0.0:80:3000
      - 0.0.0.0:9999:9999
    volumes: 
      - ./src:/www/src
    working_dir: /www/src
    command: npm start
networks:
  app:
    external: true